#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun 30 09:03:32 2019

@author: divyanshisingh
"""
import sqlite3

db=sqlite3.connect("mydb.db")
"""db.execute("create table if not exists students(rno int,name varchar(50),marks float)")
rno=int(input("enter rno"))
name=input("input name")
marks=float(input("enter marks"))
db.execute("insert into students values(?,?,?)",(rno,name,marks))
db.commit()
db.close()
"""
cursor=db.execute("select * from students")
print("hello")
for row in cursor:
    print(str(row[0])+"\t"+row[1]+"\t"+str(row[2]))
db.close()


